server/config/routes.rb
Rails.application.routes.draw do
  namespace :turbo do
    namespace :ios do
      resources :configurations, only: [] do
        get :ios_v1, on: :collection
      end
    end
  end
  resources :todos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "todos#index"
end

server/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

server/app/models/todo.rb
class Todo < ApplicationRecord
  after_create_commit -> { broadcast_append_later_to :todos }
  after_update_commit -> { broadcast_replace_later_to self }
  after_destroy_commit -> { broadcast_remove_to :todos }
end

server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

server/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:title, :complete)
    end
end

server/app/controllers/turbo/ios/configurations_controller.rb
module Turbo
  module Ios
    class ConfigurationsController < ApplicationController
      def ios_v1
        render json: {
          settings: {},
          rules: [
            {
              patterns: [
                "/new$",
                "/edit$"
              ],
              properties: {
                context: "modal"
              }
            },
            {
              patterns: [
                "/native_todos$"
              ],
              properties: {
                "view-controller": "todos"
              }
            }
          ]
        }
      end
    end
  end
end

server/app/helpers/application_helper.rb
module ApplicationHelper
end

server/app/helpers/todos_helper.rb
module TodosHelper
end

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Server</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.css", date-turbo-track='reload'>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

server/app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :complete, style: "display: block" %>
    <%= form.check_box :complete %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

server/app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>">
  <p>
    <strong>Title:</strong>
    <%= todo.title %>
  </p>

  <p>
    <strong>Complete:</strong>
    <%= todo.complete %>
  </p>

</div>

server/app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Show this todo", @todo %> |
  <%= link_to "Back to todos", todos_path %>
</div>

server/app/views/todos/index.html.erb
<%= turbo_stream_from :todos %>
<p style="color: green"><%= notice %></p>

<h1>Todos</h1>

<div id="todos">
  <% @todos.each do |todo| %>
    <%= render todo %>
    <p>
      <%= link_to "Show this todo", todo %>
    </p>
  <% end %>
</div>

<%= link_to "New todo", new_todo_path %>
<% if turbo_native_app? %>
  <%= link_to "Native todo", '/native_todos' %>
<% end %>

server/app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Back to todos", todos_path %>
</div>

server/app/views/todos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo %>

<div>
  <%= link_to "Edit this todo", edit_todo_path(@todo) %> |
  <%= link_to "Back to todos", todos_path %>

  <%= button_to "Destroy this todo", @todo, method: :delete %>
</div>